apiVersion: v1
kind: Service
metadata:
  name: nfc-ingestion-backend-qa-svc
  namespace: nfc-staging
  labels:
    app: nfc-ingestion-backend-qa
spec:
  type: ClusterIP
  selector:
    app: nfc-ingestion-backend-qa
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
